name: Check Markdown links

on: 
  workflow_dispatch:  # Manual trigger
  # push - currently disabled

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        # config-file: '.github/workflows/mcl_config.json'
        use-verbose-mode: 'yes'
